### ISSUE TITLE
TAU - Behavior Driven Python with pytest-bdd - Ch.7 - images

### ISSUE THREAD

**Issue by Rentis** [AndyLPK247/tau-pytest-bdd#1]
Hi Andrew,

I do not know if it is already mentioned but in TAU - Behavior Driven Python with pytest-bdd (https://testautomationu.applitools.com/behavior-driven-python-with-pytest-bdd/chapter7.html#test-web-steps-py) I see that the definition of files with the releated images in Transcripted Summary, Chapter 7, "test_web_steps.py" comes with the screenshot of "web.feature" and "web.feature" with the one of "test_web_steps.py". Please check.
<img width="386" alt="issue_screenshot_2" src="https://user-images.githubusercontent.com/46710269/69947178-65720f80-14ed-11ea-8463-34e9d6adc582.png">
<img width="401" alt="issue_screenshot_1" src="https://user-images.githubusercontent.com/46710269/69947180-660aa600-14ed-11ea-8450-b818715f654e.png">

Hope this is the right way to declare this issue. ( I am new in this  :-) )

Best Regards,
Nikos

**Comment by AndyLPK247** [comment]
Thanks for letting me know. I'll see what I can do to get this fixed.

**Comment by AndyLPK247** [comment]
Update request submitted to TAU.
