### ISSUE TITLE
target_fixture now has to be explicitly defined

### ISSUE THREAD

**Issue by arkaydeus** [AndyLPK247/tau-pytest-bdd#3]
In the first example of 'given' there is no reference to target_fixture. In modern versions of pytest-bdd you have to state this:

```python
@given("the basket has 2 cucumbers", target_fixture='basket')
def basket():
    return CucumberBasket(initial_count=2)
```

In the above example, without the `target_fixture='basket'`, the test will fail saying that basket is not defined. Basically given decorators no longer automatically produce fixtures without specifically stating their name using the target.

It's a bit annoying to make the changes and I realise your guides, repos were based on a previous version, but seeing as you're basically THE go to resource on the internet for pytest-bdd learning, it would be very helpful for new learners, if you updated.

I don't want to do a PR because you have video content referencing the original syntax etc.

_(BTW, thanks for the great content.)_

**Comment by AndyLPK247** [comment]
Shoot. I'll fix it. Thanks for bringing it to my attention.

**Comment by AndyLPK247** [comment]
Fixed in the example code. I'll see what I can do about fixing the TAU course content.
