### ISSUE TITLE
target_fixture='basket' doesn't seem to be working when introducing parametrize.

### ISSUE THREAD

**Issue by Robbie1478** [AndyLPK247/tau-pytest-bdd#5]
In Chapter 4 - Parametrizing Steps I seem to be having issues incorporating **target_fixture='basket'** to work alongside the changes.

Unsure if this is an issue, or because I am a total newbie and not quite grasped things all that well as yet.  
I did have this working in the Chapter 3 Tutorials.

I am essentially stuck at 4 Mins 36 Seconds where you run the tests for the first time, are you able to confirm if this is an issue, or i am doing things incorrectly in the @given step.

**Some variations I have tried:**
`@given(parsers.cfparse('the basket has "{initial:Number}" cucumbers', extra_types=dict(Number=int), target_fixture='basket')) 
def basket(initial):
    return CucumberBasket(initial_count=initial)`

`@given(parsers.cfparse('the basket has "{initial:Number}" cucumbers', target_fixture='basket' extra_types=dict(Number=int))) 
def basket(initial):
    return CucumberBasket(initial_count=initial)`

After watching further into the video things change a bit, but the same doesn't seemingly work either
`@given(parsers.cfparse('the basket has "{initial:Number}" cucumbers', target_fixture='basket', extra_types=EXTRA_TYPES))
def basket(initial):
    return CucumberBasket(initial_count=initial)`

`@given(parsers.cfparse('the basket has "{initial:Number}" cucumbers', extra_types=EXTRA_TYPES, target_fixture='basket'))
def basket(initial):
    return CucumberBasket(initial_count=initial)`

**Comment by AndyLPK247** [comment]
Hey @Robbie1478! I'm glad to see that you're trying things.

I think `target_fixture` is a parameter for the step attribute `@given` and not for the parser call. Try something like this:

```python
@given(parsers.cfparse('the basket has "{initial:Number}" cucumbers', extra_types=dict(Number=int)), target_fixture='basket')
def basket(initial):
    return CucumberBasket(initial_count=initial)
```

`@given` should have two arguments: the `parsers.cfparse` call and the `target_fixture` value. Notice the placement of parentheses and commas.

Please give this a try and let me know if it works. If it does, then please close the issue. Thanks!

**Comment by Robbie1478** [comment]
Hey @AndyLPK247 - thank you so much for the response 👍 

Would seem I tried everything but your suggestion as I was trying to put everything within the existing brackets.

That worked a treat - thanks!

Would you have any issue with my looking to submit PR for this into your Chapter 4 Branch (I could potentially update Chapter 3 to include the target_fixutre too?
Of course - equally happy not to if your intention is for people to try figure it out for themselve first.

**Comment by pl-aknight** [comment]
I'll take care of it.

**Comment by AndyLPK247** [comment]
@Robbie1478, everything should be updated and fixed now. I made some other improvements along the way.

**Comment by Robbie1478** [comment]
Thank you @AndyLPK247 - that was a quick turn around.
